spring.application.name: inspirance-backend

logging:
  file:
    name: inspirance-backend.log
  logback:
    rollingpolicy:
      max-history: 5
      max-file-size: 10MB

server:
  port: 8102
  servlet:
    context-path: /api

spring:
  boot:
    admin.client:
      url: http://localhost:8084
  datasource:
    url: ${INSPIRANCE_DATASOURCE_URL:jdbc:postgresql://localhost:5432/inspirance}
    username: ${INSPIRANCE_DATASOURCE_USERNAME:inprnc}
    password: ${INSPIRANCE_DATASOURCE_PASSWORD:inprnc1}
  jpa:
    properties.hibernate:
      jdbc.lob.non_contextual_creation: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: create
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  endpoints:
    web.exposure:
      include: "health,logfile,info"
  endpoint:
    health.show-details: always
